### ISSUE TITLE
Publish for Scala 2.12

### ISSUE THREAD

**Issue by stanch** [drdozer/graphviz-s#15]
Pretty please :)

**Comment by mushtaq** [comment]
yes, please!

**Comment by stanch** [comment]
@drdozer Do you have any plans to publish this for `2.12`? If not, do you mind if I fork the project and publish to my own bintray repo?

**Comment by drdozer** [comment]
please fork -- I don't have the time for the forseeable future to maintain this, although I would love to

**Comment by stanch** [comment]
Just a small update. Since I only needed a DSL to generate dot, I figured it was easier to implement my own than to maintain a fork. For the record, here it is, around 100 LOC: https://github.com/stanch/reftree/blob/master/core/src/main/scala/reftree/graph/Dot.scala.

**Comment by drdozer** [comment]
No problem. This project is essentially dead at this time. It's among the many things I hope to get the time to revisit one day but you are probably better off in all honesty doing it the way you have.
