### ISSUE TITLE
Publish to repository

### ISSUE THREAD

**Issue by TimSoethout** [drdozer/graphviz-s#7]
Great work. Is it possible that this will be published to a repo, so I (and others) can easily use it in my projects?

**Comment by drdozer** [comment]
Hi Tim,

It should be published to my bintray maven repo:

http://dl.bintray.com/content/drdozer/maven

Matthew

**Comment by TimSoethout** [comment]
Cheers. I did not find it yet. I added instruction for this in this pull request: https://github.com/drdozer/graphviz-s/pull/8
